"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { MainHeader } from "@/app/components/main-header";

type Category = { id: string; nome: string; descricao?: string | null; ativo: boolean; createdAt: string };
type Me = { manager: { role: "ADMIN" | "GESTOR" | "FORNECEDOR" } };

export default function CategoriasFornecedoresPage() { const [me, setMe] = useState<Me | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [form, setForm] = useState({ nome: "", descricao: "" }); const [message, setMessage] = useState(""); const router = useRouter();
const loadData = useCallback(async () => { const meRes = await fetch("/api/auth/me"); if (!meRes.ok) return router.push("/login"); setMe(await meRes.json()); const res = await fetch("/api/categorias-fornecedores"); if (res.ok) setCategories(await res.json()); }, [router]);
useEffect(() => { loadData(); }, [loadData]);
async function createCategory(e: React.FormEvent) { e.preventDefault(); const res = await fetch("/api/categorias-fornecedores", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!res.ok) return setMessage("Erro ao criar categoria."); setForm({ nome: "", descricao: "" }); setMessage("Categoria criada com sucesso."); await loadData(); }
async function toggleCategory(category: Category) { const res = await fetch(`/api/categorias-fornecedores/${category.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ativo: !category.ativo }) }); if (!res.ok) return setMessage("Erro ao atualizar categoria."); await loadData(); }
if (!me) return null; if (me.manager.role !== "ADMIN") return <main className="container container-wide"><p>Acesso restrito a ADMIN.</p></main>;
return <main className="container container-wide"><MainHeader title="Categorias de fornecedores" subtitle="Gestão das áreas de atuação" /><section className="card space-y-4"><form onSubmit={createCategory} className="grid gap-3 sm:grid-cols-3"><input className="rounded-lg border p-2" placeholder="Nome" value={form.nome} onChange={(e) => setForm((p) => ({ ...p, nome: e.target.value }))} required /><input className="rounded-lg border p-2" placeholder="Descrição" value={form.descricao} onChange={(e) => setForm((p) => ({ ...p, descricao: e.target.value }))} /><button type="submit">Cadastrar categoria</button></form><div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-sm"><thead><tr><th className="px-4 py-2 text-left">Nome</th><th className="px-4 py-2 text-left">Descrição</th><th className="px-4 py-2 text-left">Status</th><th className="px-4 py-2 text-right">Ações</th></tr></thead><tbody>{categories.map((c) => <tr key={c.id} className="border-t"><td className="px-4 py-2">{c.nome}</td><td className="px-4 py-2">{c.descricao || "-"}</td><td className="px-4 py-2">{c.ativo ? "Ativa" : "Inativa"}</td><td className="px-4 py-2 text-right"><button className="chip" onClick={() => toggleCategory(c)}>{c.ativo ? "Inativar" : "Ativar"}</button></td></tr>)}</tbody></table></div></section>{message && <p className="message">{message}</p>}</main>; }
